field: 1609f978-7f19-41cb-bcde-3b5ea3f0605f # Le Matrix
fieldLayouts:
  6784f576-3a81-428b-ac07-6b720ee899eb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ecb36fac-bb4f-4dab-9467-447ceafd0823 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf898567-f01c-4a78-a577-95dca53e66c2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 92d611ea-4077-4289-8d5a-e77377ed5d1d
        userCondition: null
fields:
  ecb36fac-bb4f-4dab-9467-447ceafd0823: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:fe1cb603-1961-4f71-9061-0d6b2806a70b' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 2
      minRelations: 1
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:fe1cb603-1961-4f71-9061-0d6b2806a70b' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
