field: 1609f978-7f19-41cb-bcde-3b5ea3f0605f # Le Matrix
fieldLayouts:
  623be2e0-7711-4f00-a879-aafaec8f9e7f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a7943288-ec4d-4f60-844c-bd9f68b36705 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff3a2355-2560-4d7e-9050-02f19ddbc5f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cc53baf8-b887-44cf-8f88-0eaf8335b48b # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9f663b0-1a3b-4ba5-b9ba-20c861a0e124
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2cc8b992-2ad2-4953-905f-bdb0109bf820
        userCondition: null
fields:
  a7943288-ec4d-4f60-844c-bd9f68b36705: # Heading
    columnSuffix: jqiryyjf
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cc53baf8-b887-44cf-8f88-0eaf8335b48b: # Content
    columnSuffix: szzuvkpz
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: null
    name: Content
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      ckeConfig: 9b5e0e97-d86f-46b0-9310-d5c1314da820 # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: text
name: Text
sortOrder: 1
