fieldLayouts:
  e005d358-8b44-4e33-86e6-03358b8eb7b7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 45f823fd-b323-418f-89b6-52894c2f3dbe
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: bb5935e5-5b6b-47dc-9f2b-e2f7cda3c3ba
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 62ba7038-57e3-4d7d-86db-a7c8c4e5d30a
        userCondition: null
fs: files
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: thumbnails
transformSubpath: ''
