currLabel: GraphQL
customIcon: null
enabled: true
handle: graphql
icon: '@appicons/graphql.svg'
layout: b86d328e-ff85-4fb1-82c9-bd349e4751ab # Default
level: 1
newWindow: false
parent: null
prevLabel: GraphQL
prevLevel: 1
prevParent: null
prevUrl: graphql
sortOrder: 13
subnavBehaviour: null
type: craft
url: graphql
