currLabel: SEO
customIcon: null
enabled: true
handle: seo
icon: /Users/bob/Sites/scaffold/vendor/ether/seo/src/icon-mask.svg
layout: b86d328e-ff85-4fb1-82c9-bd349e4751ab # Default
level: 1
newWindow: false
parent: null
prevLabel: SEO
prevLevel: 1
prevParent: null
prevUrl: seo
sortOrder: 7
subnavBehaviour: null
type: plugin
url: seo
