currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: settings
layout: b86d328e-ff85-4fb1-82c9-bd349e4751ab # Default
level: 1
newWindow: false
parent: null
prevLabel: Settings
prevLevel: 1
prevParent: null
prevUrl: settings
sortOrder: 3
subnavBehaviour: null
type: craft
url: settings
