defaultPlacement: end
enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  cee2cb8d-9d7c-4aa0-8a12-4bdd971a0517: # Scaffold
    enabledByDefault: true
    hasUrls: true
    template: index.html.twig
    uriFormat: __home__
type: single
