defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
propagationMethod: all
siteSettings:
  cee2cb8d-9d7c-4aa0-8a12-4bdd971a0517: # Scaffold
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: 'pages/{slug}'
type: channel
